name: Flutter Integration Tests
on:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: challenge
    steps:
      - name: Get Repository
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      - name: Flutter action
        uses: subosito/flutter-action@v2.10.0
        with:
          channel: "stable"

      - name: Run Flutter Pub Get
        run: flutter pub get

      - name: Unit tests
        run: flutter test test/

      # - name: Integration tests
      #   run: flutter test integration_test/

      - name: Release Android build
        run: flutter build appbundle

      - name: Upload Android Release
        uses: actions/upload-artifact@v2
        with:
          name: android-release
          path: build/app/outputs/bundle/release/app-release.aab
